[manager]
ratio = [ 1, 3, 3 ]
linemode = "mtime"
show_symlink = true

[opener]
edit = [ { run = 'nvim "$@"', block = true } ]
play = [ { run = 'vlc "$@"', orphan = true } ]
image = [ { run = 'imv "$@"', orphan = true } ]
pdf = [ { run = 'evince "$@"', orphan = true } ]

[open]
prepend_rules = [
  { name = "*.png", use = "image" },
  { name = "*.jpg", use = "image" },
  { name = "*.jpeg", use = "image" },
  { name = "*.pdf", use = "pdf" },
]
